#!/bin/bash
update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=/tmp/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

srx=$(update /sys/class/net/wlp1s0/statistics/rx_bytes)
stx=$(update /sys/class/net/wlp1s0/statistics/tx_bytes)

rx=$(cat /sys/class/net/wlp1s0/statistics/rx_bytes)
tx=$(cat /sys/class/net/wlp1s0/statistics/tx_bytes)

usage=$(echo $[$rx+$tx])
echo \DN $(numfmt --to=iec $srx) \UP $(numfmt --to=iec $stx) \USG $(numfmt --to=iec $usage)
