#!/bin/bash

layout=$(swaymsg -t get_inputs | grep "xkb_active_layout_name" | head -n1 | cut -d: -f2 | cut -d, -f1 | cut -d\" -f2)
echo $layout
if [ "$1" == "-p" ];
then 
	echo $layout
else

	if [ "$layout" == "English (US)" ];
	then
		echo swaymsg input type:keyboard xkb_layout us\(colemak\)
		swaymsg input type:keyboard xkb_layout us\(colemak\)
	else
		echo swaymsg input type:keyboard xkb_layout us
		swaymsg input type:keyboard xkb_layout us
	fi
fi	
